version: 2.1

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-libraries:
          matrix:
            parameters:
              library:
                - "storybook-addon-badges"
                - "storybook-addon-iframe"

      - test

jobs:
  test:
    working_directory: ~/geometricpanda
    docker:
      - image: cimg/node:14.16.0

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint
          command: yarn affected:lint

      - run:
          name: Test
          command: yarn affected:test --codeCoverage

      - store_artifacts:
          path: coverage
          destination: coverage

      - store_test_results:
          path: clover.xml

  build-libraries:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    parameters:
      library:
        type: string

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build
          command: yarn nx build << parameters.library >>

      - store_artifacts:
          path: dist/libs
          destination: libs
