version: 2.1

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test-libraries:
          matrix:
            parameters:
              library:
                - "storybook-addon-badges"
                - "storybook-addon-iframe"

jobs:

  build-and-test-libraries:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    parameters:
      library:
        type: string

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint
          command: yarn lint << parameters.library >>

      - run:
          name: Test
          command: yarn test << parameters.library >>

      - run:
          name: Build
          command: yarn build << parameters.library >>

      - run:
          name: List
          command: ls -als

      - store_artifacts:
          path: dist/libs/<< parameters.library >>
          destination: << parameters.library >>

      - store_artifacts:
          path: coverage/libs/<< parameters.library >>
          destination: coverage/<< parameters.library >>

      - store_test_results:
          path: coverage/libs/<< parameters.library >>
