version: 2.1

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test-libraries:
          matrix:
            parameters:
              library:
                - "storybook-addon-badges"
                - "storybook-addon-iframe"

      - build-storybook:
          requires:
            - build-and-test-libraries
jobs:

  build-storybook:

    parameters:
      libraries:
        type: string
        description: Libraries to include in yarn link
        default: "storybook-addon-badges storybook-addon-iframe"

    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - attach_workspace:
          at: ~/geometricpanda

      - run:
          name: Install Libraries to Mono Repo
          command: |
            for library in << parameters.libraries >> {
              yarn add ./dist/libs/$library --frozen-lockfile
            }

  build-and-test-libraries:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    parameters:
      library:
        type: string

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint
          command: yarn lint << parameters.library >>

      - run:
          name: Test
          command: yarn test << parameters.library >> --codeCoverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: coverage/libs/<< parameters.library >>

      - run:
          name: Build
          command: yarn build << parameters.library >>

      - persist_to_workspace:
          root: ~/geometricpanda
          paths:
            - dist/libs/<< parameters.library >>

      - store_test_results:
          path: coverage/libs/<< parameters.library >>
