version: 2.1

parameters:
  libraries:
    type: string
    description: Libraries
    default: "storybook-addon-badges storybook-addon-iframe"

workflows:
  version: 2

  build:
    jobs:
      - build-libraries:
          matrix:
            parameters:
              library:
                - "storybook-addon-badges"
                - "storybook-addon-iframe"

      - build-storybook:
          requires:
            - build-libraries

      - approve-storybook:
          type: approval
          filters:
            branches:
              only: /release\/.*/

          requires:
            - build-storybook

      - approve-libraries:
          type: approval
          filters:
            branches:
              only: /release\/.*/

          requires:
            - build-libraries

      - deploy-libraries:
          filters:
            branches:
              only: /release\/.*/

          matrix:
            parameters:
              library:
                - "storybook-addon-badges"
                - "storybook-addon-iframe"

          requires:
            - approve-libraries

      - deploy-storybook:
          filters:
            branches:
              only: /release\/.*/

          requires:
            - approve-storybook

jobs:

  build-storybook:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - attach_workspace:
          at: ~/geometricpanda

      - run:
          name: Install Libraries to Mono Repo
          command: |
            packagesArr=(<< pipeline.parameters.libraries >>)
            packagesAcc="";

            for package in "${packagesArr[@]}"
            do
                packagesAcc="${packagesAcc} @geometricpanda/${package}";
                cd ~/geometricpanda/dist/libs/${package};
                yarn link;
            done

            cd ~/geometricpanda;
            yarn link ${packagesAcc} --frozen-lockfile;
      - run:
          name: Build Storybook
          command: yarn nx run geometricpanda:build-storybook:ci

      - persist_to_workspace:
          root: ~/geometricpanda
          paths:
            - dist/storybook

  build-libraries:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    parameters:
      library:
        type: string

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint
          command: yarn lint << parameters.library >>

      - run:
          name: Build
          command: yarn build << parameters.library >>

      - run:
          name: Sync Package JSONS
          command: |
            npx --no-install sync-json -v --property version --source package.json dist/libs/<< parameters.library >>/package.json

      - persist_to_workspace:
          root: ~/geometricpanda
          paths:
            - dist/libs/<< parameters.library >>

  deploy-libraries:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    parameters:
      library:
        type: string

    steps:
      - attach_workspace:
          at: ~/geometricpanda

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - run:
          name: Deploy Package
          command: |
            npm publish dist/libs/<< parameters.library >> --access public


  deploy-storybook:
    working_directory: ~/geometricpanda

    docker:
      - image: cimg/node:14.16.0

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - attach_workspace:
          at: ~/geometricpanda

      - run:
          name: Add Netlify CLI
          command: |
            npm init --force &> /dev/null;
            yarn add netlify-cli --dev

      - run:
          name: Deploy to Netlify
          command: |
            npx --no-install netlify deploy --dir dist/storybook/geometricpanda --prod
