name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  pipeline:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        libs:
          - storybook-addon-badges

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint - ${{ matrix.libs }}
        run: yarn nx lint ${{ matrix.libs }}

      - name: Unit Test - ${{ matrix.libs }}
        run: yarn nx test ${{ matrix.libs }} --codeCoverage

      - name: Build Library - ${{ matrix.libs }}
        run: yarn nx build ${{ matrix.libs }}

      - name: Ensure package.json version matches tag - ${{ matrix.libs}}
        run: npm version ${{ env.TAG }} --prefix ./libs/${{ matrix.libs}} --allow-same-version

      - name: Release Package - ${{ matrix.libs }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/${{ matrix.libs }}/package.json
          check-version: true
          access: public
